#香满园 端口配置
app:
  name: "web_app"
  mode: "dev"
  port: 7777
  version: "v1"

#日志
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 300  #每个人日志文件大小
  max_age: 30    #存储天数
  max_backups: 7 #备份数量

#数据库 配置
mysql:
  host: "118.31.21.183"
  port: "3306"
  user: "telegram"
  password: "rbmweMypmiNhEHbk"
  dbname: "telegram"


#redis  配置
redis:
  host: "118.31.21.183"
  port: 6379
  db: 9
  password: "xnkr5de27fkPB8Et"
  pool_size: 20


